version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=drug
      - MYSQL_USER=rankey
      - MYSQL_PASSWORD=rankey
      - MYSQL_ROOT_PASSWORD=rankey
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: